[tool.bandit]
exclude_dirs = []

[tool.black]
color = true

[tool.coverage.run]
omit = []
source = ["sops"]

[tool.coverage.report]
show_missing = true

[tool.isort]
color_output = true
profile = "black"
skip = []

[tool.pylint.master]
ignore = []
output-format = "colorized"

[tool.pytest.ini_options]
addopts = "--color=yes --ignore=examples/ --verbose"
