name: Checks

on:
  pull_request:
    branches:
    - python-sops
  push:
    branches:
    - python-sops

env:
  PY_COLORS: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - flake8
        #- isort
        #- black
        #- bandit
        #- pylint
        - requirements
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install build tools
      run: python -m pip install --disable-pip-version-check tox wheel
    - name: Install system dependencies
      run: scripts/install/prerequisites
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
